version: '3.3'

services:

  php-fpm:
    build: ./devops/docker/services/php-fpm
    container_name: "${PROJECT_NAME}${PROJECT_SEPARATOR}php-fpm"
    environment:
      WORKDIR_PROJECT: "/var/www/html"
    volumes:
      - ${PROJECT_DEFAULT_HOST}:${PROJECT_DEFAULT_CONTAINER}

  apache:
    build: ./devops/docker/services/apache
    container_name: "${PROJECT_NAME}${PROJECT_SEPARATOR}apache"
    environment:
      FPM_HOST: "${PROJECT_NAME}${PROJECT_SEPARATOR}php-fpm:9000"
    volumes:
      - ./devops/docker/config/apache2/sites-enabled:/etc/apache2/sites-enabled
      - ${PROJECT_DEFAULT_HOST}:${PROJECT_DEFAULT_CONTAINER}
    ports:
      - 7000:80

  mysql:
    image:  mysql:5.7
    container_name: "${PROJECT_NAME}${PROJECT_SEPARATOR}mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "${PROJECT_NAME}${PROJECT_SEPARATOR}db"
      MYSQL_DATABASE: "${PROJECT_NAME}${PROJECT_SEPARATOR}db"
      MYSQL_USER: "${PROJECT_NAME}${PROJECT_SEPARATOR}db"
      MYSQL_PASSWORD: "${PROJECT_NAME}${PROJECT_SEPARATOR}db"
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - ${PROJECT_DEFAULT_HOST}:${PROJECT_DEFAULT_CONTAINER}
      - ./devops/docker/volume/mysql:/var/lib/mysql
      - ./devops/docker/logs/mysql:/var/log/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "${PROJECT_NAME}${PROJECT_SEPARATOR}phpmyadmin"
    environment:
      PMA_HOST: "${PROJECT_NAME}${PROJECT_SEPARATOR}mysql"
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: "${PROJECT_NAME}${PROJECT_SEPARATOR}db"
    ports:
      - 7100:80